###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3"
services:
  php-fpm:
    build: .
    container_name: sf-skel
    ports:
      - "82:80"
    volumes:
      - .:/var/www/html